language: node_js
node_js: node

# will run `npm install` automatically here

script:
  - npm test
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then npm run build; fi'

notifications:
  email: false

cache:
  directories:
    - node_modules
    - public
