language: node_js
node_js: node

addons:
  apt:
    update: true
    packages:
      - graphviz

# will run `npm install` automatically here

script:
  - npm test
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then npm run build; fi'

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
  email: false

cache:
  directories:
    - node_modules
    - public
