version: '3'
services:
  gatsby:
    build: .
    command: ./node_modules/gatsby/dist/bin/gatsby.js develop --host 0.0.0.0
    volumes:
      - .:/docs
      - /docs/node_modules
    ports:
      - '8000:8000'
